#pragma config(Sensor, S1,     ,               sensorSONAR)
#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Motor,  motorB,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	////////////////////////////////
  nxtDisplayCenteredTextLine(3, "linia");
  nxtDisplayCenteredTextLine(4, "i am winer:)");
	float k1=1.5, //koeficent povorotlivosti
				k2=0.75,  // yskorenie
				kv=0.1;   //koeficent tormoghenia
	int 	vmax=20;
	////////////////////////////////
	int es=SensorValue[S1]-SensorValue[S3];
	int v , u ,err , errold=0, mB, mC;
	while (true)

	{
		err=SensorValue[S1]-SensorValue[S3]-es;
		u=k1*err+k2*(err-errold);
		errold=err;
		v=vmax-abs(u)*kv;
		mB=v+u;
		mC=v-u;
		if (abs(mB)>100) mB=sgn(mB)*100;
		if (abs(mC)>100) mB=sgn(mC)*100;
		motor[motorB]=mB;
		motor[motorC]=mC;
		wait1Msec(1);
	}


}
