#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorSONAR)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include<monstr.h>

task main()
{
	while(true)
	{
		motor[motorA] = 100;
		motor[motorB] = 100;
		motor[motorC] = 100;
		motor[motorD] = 100;
		if(SensorValue[S1] <= greay)
		{
			motor[motorA] = -100;
			motor[motorB] = -100;
			motor[motorC] = -100;
			motor[motorD] = -100;
			wait1Msec(500);
		}
		wait1Msec(1);
	}
}
