#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <monstr.h>

task main()
{
		wait1Msec(5000);
		while(true)
		{
			motor[motorA] = 100;
			motor[motorB] = 100;
			motor[motorC] = 100;
			motor[motorD] = 100;
			wait1Msec(1);

			if(SensorValue[S1] <= greay)
			{
				motor[motorA] = -100;
				motor[motorB] = -100;
				motor[motorC] = -100;
				motor[motorD] = -100;
				wait1Msec(1000);
			}
	 	}

	 	motor[motorA] = 0;
	 	motor[motorB] = 0;
	 	motor[motorC] = 0;
	 	motor[motorD] = 0;
}
