#pragma config(Sensor, S1,     ,               sensorSONAR)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	#include <monstr.h>
	while(SensorValue[S4] == 0) wait1Msec(1);

	wait1Msec(5000);

	while(SensorValue[S1] >= 25)
	{
		motor[motorA] = -100;
		motor[motorB] = -100;
		motor[motorC] = 100;
		motor[motorD] = 100;
		//if(SensorValue[S2] > 0) break;
		//nxtDisplayString(5,"%s", name);
		wait1Msec(1);
	}

	nMotorEncoder[motorC] = 0;

	while(nMotorEncoder[motorC] <= 300)
	{
		motor[motorA] = -100;
		motor[motorB] = -100;
		motor[motorC] = 100;
		motor[motorD] = 100;
	}

	while(true)
	{
		motor[motorA] = 100;
		motor[motorB] = 100;
		motor[motorC] = 100;
		motor[motorD] = 100;
		if(SensorValue[S2] <= greay || SensorValue[S3] <= greay) break;
		wait1Msec(1);
	}

		while(nMotorEncoder[motorC] >= -300)
	{
		motor[motorA] = -100;
		motor[motorB] = -100;
		motor[motorC] = -100;
		motor[motorD] = -100;
	}
}
