#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <line.h>

task main()
{
	//go_line(
	///* k1 */1.55,
	///* k2 */30,
	///* kv */0.55,
	///* vm */60
	//);
	turn_forward(100,350);
	turn_left(100,350);
	go_line_wall(
	/* k1 */1.55,
	/* k2 */30,
	/* kv */0.55,
	/* vm */60,
	/* so */15
	);
	turn_left(100,200);
	turn_forward(100,400);
	turn_right(100,200);
	turn_forward(100,750);
	turn_right(100,255);
	turn_forward(100,100);
	turn_left(100,400);
	turn_forward(100,100);
	turn_right(100,125);
	turn_forward(100,750);
	turn_right(100,190);
	turn_forward(100,250);
	turn_left(100,250);
	//turn_back(100,19);
	shot();
	go_line(
	/* k1 */1.55,
	/* k2 */30,
	/* kv */0.55,
	/* vm */60
	);
	turn_left(100,100);
	turn_forward(100,850);
	turn_right(100,100);
	go_line(
	/* k1 */1.55,
	/* k2 */30,
	/* kv */1.55,
	/* vm */60
	);
	turn_forward(100,100);
	turn_right(100,100);
	go_line(
	/* k1 */1.55,
	/* k2 */30,
	/* kv */0.55,
	/* vm */60
	);
	turn_forward(100,600);
	go_line(
	/* k1 */1.55,
	/* k2 */30,
	/* kv */0.55,
	/* vm */60
	);
}
