#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <gyro.h>
#include <sumo.h>
#include <motors.h>

task main()
{
	wait1Msec(5000);
	search_l(40,40);
	turn_left(40,40);
	sumo_walking();
}
