#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorTouch)
#pragma config(Motor,  motorB,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	////////////////////////////////
  nxtDisplayCenteredTextLine(3, "linia");
  nxtDisplayCenteredTextLine(4, "i am winer:)");
	float k1=1.5, //koeficent povorotlivosti
				k2=30,  // yskorenie
				kv=1;   //koeficent tormoghenia
	int 	vmax=70;
	int   grey = 50;
	////////////////////////////////
	int es=SensorValue[S1]-SensorValue[S2];
	int v , u ,err , errold=0, mB, mC;
	while (true)

	{
		err=SensorValue[S1]-SensorValue[S2]-es;
		u=k1*err+k2*(err-errold);
		errold=err;
		v=vmax-abs(u)*kv;
		mB=v+u;
		mC=v-u;
		if (abs(mB)>100) mB=sgn(mB)*100;
		if (abs(mC)>100) mB=sgn(mC)*100;
		motor[motorB]=mB;
		motor[motorC]=mC;


		if(SensorValue[S1] < grey && SensorValue[S2] < grey)
			{
				while(true)
				{
					motor[motorB] = 0;
					motor[motorC] = 0;

					if(SensorValue[S3] == 1)
					{
						motor[motorB] = 50;
						motor[motorC] = 50;
						wait1Msec(300);
						break;
					}
				}
		}

		wait1Msec(1);
	}


}
