#pragma config(Sensor, S2,     ,               sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int standart_value = SensorRaw[S2];
int err, errold = 0;
float kp = 1;
float ki = 0.000;
float kd = 10;
float scale = 1;
float dt = 1;
float p, i = 0, d, u;
int time;

task main()
{
	sensorReset(S2);
	getGyroDegrees(S2);

	while(true)
	{
		//if(u == -1) u = 1;
    SensorValue[S2] = SensorValue[S2] + 5;
		err = standart_value -  SensorValue[S2];
		p = kp * err;
		i = i + ki * err * dt;
		d = kd * (err - errold);
		errold  = err;
		u  = (p + i + d)/scale;
		motor[motorB] =  - u;
		motor[motorC] =  - u;
		wait1Msec(1);

		/*if(p <= 10 && p >= -10) time++;
		else time = 0;


		if( p <= 10 && p >= -10 && time >= 1000)
		{
			if(nMotorEncoder[motorB] > 0)
			{
				while(nMotorEncoder[motorB] > 0)
				{
					motor[motorB] = -20;
					motor[motorC] = -20;
				}
			}

			if(nMotorEncoder[motorB] < 0)
			{
				while(nMotorEncoder[motorB] < 0)
				{
					motor[motorB] = 20;
					motor[motorC] = 20;
				}
			}

			if(nMotorEncoder[motorB] = 0)
			{
				motor[motorB] = 0;
				motor[motorC] = 0;
			}
		}*/

		displayBigTextLine(0, "%d", SensorValue[S2]);
		displayBigTextLine(3, "%f", p);
		displayBigTextLine(5, "%f", i);
		displayBigTextLine(5, "%d", time);
		displayBigTextLine(10, "%f", d);
		displayBigTextLine(13, "%f", u);

	}


}
