
#pragma config(Sensor, S1,     t1,             sensorTouch)
#pragma config(Sensor, S2,     t2,             sensorTouch)
#pragma config(Sensor, S3,     t3,             sensorTouch)
#pragma config(Sensor, S4,     t4,             sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	///////////////////////////////////////////////////////////////////////////////
	short	encoderB_old=0,encoderC_old=0,u=0,time=20,timeC=0,timeB=0,timeBig=6,timeM=500;
	float Am=0,y=0,k=0.02,w=7,lconf=0.05;
	char t=1,o=1,leftPlayer=0,rightPlayer=0,n=0,xB=10,yB=30,xT=15,yT=35;//ball
	char RxT,RyT,RxB,RyB,Rn,lxT,lyT,lxB,lyB,ln;//rocket
	char *RxTPointer=&RxT;
	////////////////////////////////////////////////////////////////////////////////

	nMotorEncoder[motorB]=0;
	nMotorEncoder[motorC]=0;
	while((leftPlayer!=10)&&(rightPlayer!=10)){
		//y=k(x+n)+t;
		//y=1*(x+20)+30

		//ball move
		y=Am*t;
		if ((xT<=99)&&(xT>=5)&&(o==1)) {
   	xT=round (xT+t);
		yT=round (yT+y);
		xB=round (xB+t);
		yB=round (yB+y);
		}
		if ((xT<=99)&&(xT>=5)&&(o==-1)) {
		xT=round (xT-t);
		yT=round (yT+y);
		xB=round (xB-t);
		yB=round (yB+y);

		}
		if (yT>63){Am=abs(Am)*(-1);}
		if (yB<0) {Am=abs(Am);}

	/*	y=Am*t;
		xT=round (5+t);
		yT=round (5+y+yl);
		xB=round (0+t);
		yB=round (0+y+yl);*/
		FillEllipse(xT,yT,xB,yB);

		//right rocket function
		Rn=round(nMotorEncoder[motorC]/5);
		RxT=94;
		RyT=45+Rn;
		RxB=96;
		RyB=30+Rn;
		FillRect(*RxTPointer,RyT,RxB,RyB);

		//lest rocket function
		ln=round(nMotorEncoder[motorB]/5);
		lxT=3;
		lyT=45+ln;
		lxB=5;
		lyB=30+ln;
		FillRect(lxT,lyT,lxB,lyB);

		//reflection function
		//if ((yB>=RyB)&&(yT<=RyT)&&(RxT==xB+4)&&(o==1)) 	{o=o*(-1);}
		//if ((yB>=lyB)&&(yT<=lyT)&&(lxB==xB)&&(o==-1))	 	{o=o*(-1);}
		if ((yT+2>=RyB)&&(yB-2<=RyT)&&(RxT==xB+4)&&(o==1))		{o=o*(-1);
																													Am=Am+(((RyT-((yT+yB)/2))-(((yT-yB)/2)-RyB))*k)+((random(21)-10)*lconf);
																													/*time=time+((nMotorEncoder[motorC]-encoderC_old)*w);*/
																													timeC=n+w;}
		if ((yT+2>=lyB)&&(yB-2<=lyT)&&(lxT==xB)&&(o==-1))  		{o=o*(-1);
																													Am=Am+(((RyT-((yT+yB)/2))-(((yT-yB)/2)-RyB))*k)+((random(21)-10)*lconf);
																													/*time=time+((nMotorEncoder[motorB]-encoderB_old)*w);*/
																													timeB=n+w;}


		//points count
		DisplayStringAt(30,55,"%d",leftPlayer);
		DisplayStringAt(61,55,"%d",rightPlayer);
		//nxtDisplayStringAt(1*0,10,"%d",Am);
		//nxtDisplayStringAt(30,20,"%d",u);
		if (timeC>n){time=time-timeBig;timeC=timeC-1;} else {time=20;}
		if (timeB>n){time=time-timeBig;timeC=timeC-1;} else {time=20;}
	//pause
		if ((SensorValue[t1]==1)||(SensorValue[t2]==1)||(SensorValue[t3]==1)||(SensorValue[t4]==1))
	{
		wait1Msec(200);
		while ((SensorValue[t1]!=1)&&(SensorValue[t2]!=1)&&(SensorValue[t3]!=1)&&(SensorValue[t4]!=1))
			{
				DisplayStringAt(30,40,"pause");
				wait1Msec(20);
			}
			DisplayBigStringAt(48,40,"3");
			wait1Msec(1000);
			DisplayBigStringAt(48,40,"2");
			wait1Msec(1000);
			DisplayBigStringAt(48,40,"1");
			wait1Msec(1000);
		}

	//timer
		wait1Msec(time);
		eraseDisplay();

		//fall
		if (xT==99) {o=-1;leftPlayer=leftPlayer+1;}
		if (xT==5)  {o=1;rightPlayer=rightPlayer+1;}

		if (Am<=-1.7) {Am=-1.7;}
		if (Am>=1.7)  {Am=1.7;}
		if (Am<=-1.3) {Am=Am+0.1;}
		if (Am>=1.3) {Am=Am-0.1;}

		u++;
		//spead
		encoderB_old=nMotorEncoder[motorB];
		encoderC_old=nMotorEncoder[motorC];
		time=time-round(u/timeM);
		if (time<10) {time=10;}
		}
	//points count
	if ((leftPlayer==10)||(rightPlayer==10)){
		if(leftPlayer<rightPlayer) {DisplayCenteredTextLine(3,"Right player");
															  DisplayCenteredTextLine(4,"is WIN!");
																DisplayStringAt(45,20,"%d",u);
																wait1Msec(2000);}

	  if(leftPlayer>rightPlayer) {DisplayCenteredTextLine(3,"Left player");
															  DisplayCenteredTextLine(4,"is WIN!");
															  DisplayStringAt(45,20,"%d",u);
															  wait1Msec(2000);}}
}
