#pragma config(Sensor, S1,     l1,             sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S2,     l2,             sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S3,     s1,             sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     s2,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

char n=0,k=0,sonar=40,greay=40;
task main()
{
while (true){
while (SensorValue[s1]>sonar)
{
	motor[motorC]=100;
	motor[motorB]=-100;
	wait1Msec(1);
}
n=0;	k=0;

		 while (k+n!=2)
		 {

		  if (SensorValue[l1]<greay) n=1;
		  if (SensorValue[l2]<greay) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			wait1Msec(1);

	}

	motor[motorA]=0;
	motor[motorB]=0;
	motor[motorC]=0;
	wait1Msec(100);




}}
