#pragma config(Sensor, S1,     l1,             sensorLightActive)
#pragma config(Sensor, S2,     s1,             sensorSONAR)
#pragma config(Sensor, S3,     l2,             sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int n=0 , k=0, greay=30,sonar=40;
	while (nNxtButtonPressed==-1) {
		wait1Msec(1);
	}
	//forward
	if (nNxtButtonPressed==3) {
		 nxtDisplayCenteredTextLine(3, "forward");

		 while (k+n!=2) {
		  if (SensorValue[l1]<greay) n=1;
		  if (SensorValue[l2]<greay) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			wait1Msec(1);

	}}

//povorot 90 deg
	if (nNxtButtonPressed==2){
		 nxtDisplayCenteredTextLine(3, "90");
	while (SensorValue[s1]>sonar)
{ nxtDisplayCenteredTextLine(3, "90");
	motor[motorC]=100;
	motor[motorB]=-100;
	wait1Msec(1);
}
n=0;	k=0;

		 while (k+n!=2) {
		   nxtDisplayCenteredTextLine(3, "90");
		  if (SensorValue[l1]<greay) n=1;
		  if (SensorValue[l2]<greay) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			wait1Msec(1);

	}
	nxtDisplayCenteredTextLine(3, "90");
	motor[motorA]=0;
	motor[motorB]=0;
	motor[motorC]=0;
	wait1Msec(100);

}
	//povorot 180 deg
	if (nNxtButtonPressed==1){
		 nxtDisplayCenteredTextLine(3, "180");
		 wait1Msec(1000);
	}

}
