#pragma config(Sensor, S1,     l1,             sensorLightActive)
#pragma config(Sensor, S2,     s1,             sensorSONAR)
#pragma config(Sensor, S3,     l2,             sensorLightActive)
#pragma config(Sensor, S4,     g1,             sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//menu variables
bool tought1=true,tought2=true;
char type=0,sonar=48;
//robot variables
char k=0,n=0,grey=40;


//program start
task main()
{
//selection menu
while ((nNxtButtonPressed!=3)&&(tought1==true))
	{
		if (nNxtButtonPressed==1) {type=type+1;}
		if (nNxtButtonPressed==2) {type=type-1;}
		//nxtDisplayCenteredTextLine(2,"%d",type);
		if (type==0) {nxtDisplayCenteredBigTextLine(4,"forward");}
		if (type==1) {nxtDisplayCenteredBigTextLine(4,"left");}
		if (type==2) {nxtDisplayCenteredBigTextLine(4,"right");}
		if (type==3) {nxtDisplayCenteredBigTextLine(4,"round");}
		if (type<0)  {type=0;}
		if (type>3)  {type=3;}
		wait1Msec(250);
		}
		tought1=false;
		wait1Msec(300);
		eraseDisplay();
//ready menu
	while (nNxtButtonPressed!=3)
		{
		if (type==0){nxtDisplayCenteredBigTextLine(4,"forward");
								  nxtDisplayCenteredBigTextLine(1,"ready");}
		if (type==1) {nxtDisplayCenteredBigTextLine(4,"left");
									nxtDisplayCenteredBigTextLine(1,"ready");}
		if (type==2) {nxtDisplayCenteredBigTextLine(4,"right");
									nxtDisplayCenteredBigTextLine(1,"ready");}
		if (type==3) {nxtDisplayCenteredBigTextLine(4,"round");
									nxtDisplayCenteredBigTextLine(1,"ready");}
		wait1Msec(10);
		eraseDisplay();
		}
		tought2=false;
		eraseDisplay();
//start motion
//forward motion
		if (type==0) {
		while (k+n!=2) {
		  if ((SensorValue[l1]<grey)&&(SensorValue[sonar1]>sonar)) n=1;
		  if ((SensorValue[l2]<grey)&&(SensorValue[sonar1]>sonar)) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			nxtDisplayCenteredTextLine(3,"%d",SensorValue[s1]);
			nxtDisplayCenteredTextLine(2,"%d",SensorValue[l1]);
			nxtDisplayCenteredTextLine(1,"%d",SensorValue[l2]);
			wait1Msec(2);
			eraseDisplay();
	}
}
//motion left
		if (type==1) {
		while (true) {

		while (SensorValue[s1]>sonar)
{ motor[motorC]=100;
	motor[motorB]=-100;
	wait1Msec(1);
}
n=0;	k=0;

		 while (k+n!=2) {
		   nxtDisplayCenteredTextLine(3, "90");
		  if (SensorValue[l1R]<grey) n=1;
		  if (SensorValue[l2L]<grey) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			wait1Msec(1);

	}
	nxtDisplayCenteredTextLine(3, "90");
	motor[motorA]=0;
	motor[motorB]=0;
	motor[motorC]=0;
	wait1Msec(100);

		}}
//right motion
		if (type==2) {
			while (true) {
		while (SensorValue[s1]>sonar)
{ motor[motorC]=-100;
	motor[motorB]=100;
	wait1Msec(1);
}
n=0;	k=0;

		 while (k+n!=2) {
		   nxtDisplayCenteredTextLine(3, "90");
		  if (SensorValue[l1R]<grey) n=1;
		  if (SensorValue[l2L]<grey) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			wait1Msec(1);

	}
	nxtDisplayCenteredTextLine(3, "90");
	motor[motorA]=0;
	motor[motorB]=0;
	motor[motorC]=0;
	wait1Msec(100);

		}

		}
		//round motion
		if (type==3) {
			while (true) {
		while (SensorValue[s1]>sonar)
{ motor[motorC]=100;
	motor[motorB]=-100;
	wait1Msec(1);
}
n=0;	k=0;

		 while (k+n!=2) {
		   nxtDisplayCenteredTextLine(3, "90");
		  if (SensorValue[l1R]<grey) n=1;
		  if (SensorValue[l2L]<grey) k=1;
		  motor[motorA]=-100;
			motor[motorB]=100;
			motor[motorC]=100;
			wait1Msec(1);

	}
	nxtDisplayCenteredTextLine(3, "90");
	motor[motorA]=0;
	motor[motorB]=0;
	motor[motorC]=0;
	wait1Msec(100);

		}

		}


}
