
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[motorA]=-10;
wait1Msec(500);
motor[motorA]=0;
nMotorEncoder[motorA]=0;
motor[motorA]=20;
while(nMotorEncoder[motorA]<30) wait1Msec(1);
motor[motorA]=0;



while(true)
{

motor[motorA]=-80;
while(nMotorEncoder[motorA]>10) wait1Msec(1);
motor[motorA]=20;
 while(nMotorEncoder[motorA]<30) wait1Msec(1);
motor[motorA]=0;
wait1Msec(random(1000)):




}
