#pragma config(Sensor, S1,     T1,             sensorEV3_Touch)
#pragma config(Sensor, S2,     T2,             sensorEV3_Touch)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[motorA]=-10;
wait1Msec(500);
motor[motorA]=0;
nMotorEncoder[motorA]=0;
motor[motorA]=20;
while(nMotorEncoder[motorA]<30) wait1Msec(1);
motor[motorA]=0;

motor[motorB]=-10;
wait1Msec(500);
motor[motorB]=0;
nMotorEncoder[motorB]=0;
motor[motorB]=20;
while(nMotorEncoder[motorB]<30) wait1Msec(1);
motor[motorB]=0;

while(true)
{
	if (SensorValue[T1]==1)
	{
motor[motorA]=-80;
while(nMotorEncoder[motorA]>10) wait1Msec(1);
motor[motorA]=20;
 while(nMotorEncoder[motorA]<30) wait1Msec(1);
motor[motorA]=0;
}

	if (SensorValue[T2]==1)
	{
motor[motorB]=-80;
while(nMotorEncoder[motorB]>10) wait1Msec(1);
motor[motorB]=20;
 while(nMotorEncoder[motorB]<30) wait1Msec(1);
motor[motorB]=0;
}
}


}
