#pragma config(Sensor, S2,     Us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int L=SensorValue[Us];
int u;
while(true){
u=2*(SensorValue[Us]-L);
motor[mB]=50+u;
motor[mC]=50-u;
}


}
