#pragma config(Sensor, S1,     L1,             sensorEV3_Color)
#pragma config(Sensor, S2,     L2,             sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int v=50;
int left=SensorValue[L1];
int right=SensorValue[L2];
float u;
float kp=4;
float kd=0.2;
float err;

while(true){

	err=(SensorValue[L1]-left)-(SensorValue[L2]-right);
	u=kp*err+kd*err*err*err;
	motor[mB]=v+u;
	motor[mC]=v-u;
	wait1Msec(1);
}

}
