#pragma config(Sensor, S1,     Us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){ // vkl motor
		motor[mB]=50;
motor[mC]=50;
while(SensorValue[Us]>25)wait1Msec(1); //jdi prepyatstvie 25 sm
motor[mB]=-50;// motory nazad
motor[mC]=-50;
wait1Msec(500); // jdi 0.5 sec
motor[mB]=50; // motor B vpered
wait1Msec(500);
}
}
