#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward()
{
nMotorEncoder[mB]=0;// вперед
motor[mB]=50;
motor[mC]=50;
while(nMotorEncoder[mB]<500) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;
}
void right()
{
nMotorEncoder[mB]=0;//napravo
motor[mB]=50;
motor[mC]=-50;
while(nMotorEncoder[mB]<250) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;
}
void left()
{
	nMotorEncoder[mB]=0;//napravo
motor[mB]=-50;
motor[mC]=50;
while(nMotorEncoder[mB]>-250) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;
}

task main()
{
forward();
wait1Msec(500);
right();
wait1Msec(500);
forward();
wait1Msec(500);
left();
wait1Msec(500);
forward();


}
