#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
nMotorEncoder[mB]=0;// vpered
motor[mB]=50;
motor[mC]=50;
while(nMotorEncoder[mB]<500) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;

nMotorEncoder[mB]=0;//napravo
motor[mB]=50;
motor[mC]=-50;
while(nMotorEncoder[mB]<250) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;

nMotorEncoder[mB]=0;//aia?aa
motor[mB]=50;
motor[mC]=50;
while(nMotorEncoder[mB]<500) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;

nMotorEncoder[mB]=0;//iaeaai
motor[mB]=-50;
motor[mC]=50;
while(nMotorEncoder[mB]>-250) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;

nMotorEncoder[mB]=0;//aia?aa
motor[mB]=50;
motor[mC]=50;
while(nMotorEncoder[mB]<500) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;

}
