#pragma config(Sensor, S1,     Front,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Right,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward()
{
nMotorEncoder[mB]=0;// 2?5@54
motor[mB]=50;
motor[mC]=50;
while(nMotorEncoder[mB]<500) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;
}
void right()
{
nMotorEncoder[mB]=0;//napravo
motor[mB]=50;
motor[mC]=-50;
while(nMotorEncoder[mB]<250) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;
}
void left()
{
	nMotorEncoder[mB]=0;//napravo
motor[mB]=-50;
motor[mC]=50;
while(nMotorEncoder[mB]>-250) wait1Msec(1);
motor[mB]=0;
motor[mC]=0;
}

task main()
{
	while(true)
	{
if(SensorValue[Right]>15)
{
right();
wait1Msec(500);
forward();
wait1Msec(500);
}
else
{
if (SensorValue[Front]>15)
{
forward();
wait1Msec(500);
}
else
{
left();
wait1Msec(500);
}
}
}}
