#pragma config(Sensor, S1,     C1,             sensorEV3_Color)
#pragma config(Sensor, S2,     C2,             sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	while(true){
	if (SensorValue[S1]>28)
	{if (SensorValue[S2]>40)
	{
	motor[motorB]=50;
	motor[motorC]=50;
	}
	else{
		motor[motorB]=50;
	motor[motorC]=0;
	}
		}
		else{
		if (SensorValue[S2]>40)	{
		motor[motorB]=0;
	motor[motorC]=50;
		}
		else{
			motor[motorB]=50;
	motor[motorC]=50;
		}

}
wait1Msec(1);
}
}
