#pragma config(Sensor, S1,     S,              sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
	if(SensorValue[S]>30){
		motor[mB]=50;
		motor[mC]=10;
	}
	else{
	motor[mC]=50;
		motor[mB]=10;
}
wait1Msec(1);

}
}
