#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task screen()
{
	while(true)
	{
displayBigTextLine(2,"%d",nMotorEncoder[motorA]);
wait10Msec(1);
}
}
task main()
{
nMotorEncoder[motorA]=0;
startTask(screen);
while(true)
{
motor[motorA]=10;
wait10Msec(1);
}


}
