#pragma config(Sensor, S1,     S,              sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{
	int u;
while(true)
{

		u=2.5*(SensorValue[S1]-30);
		motor[mC]=100+u;
	motor[mB]=100-u;
wait1Msec(1);

}
}
