#pragma config(Sensor, S1,     C1,             sensorNone)
#pragma config(Sensor, S2,     C2,             sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int x=0;

while(x<5)
{
if(SensorValue[C1]>28){
	if(SensorValue[C2]>40){
		motor[motorB]=30;
		motor[motorC]=30;
	}
	else{
		motor[motorB]=30;
		motor[motorC]=0;
	}
	}
	else{
	if(SensorValue[C2]>40){
	motor[motorB]=0;
		motor[motorC]=30;
	}
	else{
		motor[motorB]=30;
		motor[motorC]=30;
			wait1Msec(200);
				x=x+1;
	}
}

}
nMotorEncoder[motorB]=0;
while(nMotorEncoder[motorB]<500)
{
motor[motorB]=30;
motor[motorC]=-30;
//wait1Msec(1);
}
}
