#pragma config(Sensor, S1,     S,              sensorEV3_Color)
#pragma config(Sensor, S2,     Color,          sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{
	int u;
while(true)
{

		u=2*((28-SensorValue[S1])-(40-SensorValue[S2]));
		motor[mC]=50+u;
	motor[mB]=50-u;
wait1Msec(1);

}
}
