#pragma config(Sensor, S1,     left1,          sensorEV3_Color)
#pragma config(Sensor, S2,     right2,         sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task display()
{while(true)
{
displayBigTextLine(2,"%d",motor[motorB]);
displayBigTextLine(6,"%d",motor[motorC]);
wait10Msec(1);
}
	}

	task main()

{
int u;
	int left=SensorValue[left1];
	int right=SensorValue[right2];

while(true)
{

		u=2*((SensorValue[left1]-left)-(SensorValue[right2]-right));
		motor[mC]=50+u;
	motor[mB]=50-u;
wait1Msec(1);
startTask(display);

}
}
