#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int k=2;
task main()
{
nMotorEncoder[motorA]=0;
while(true)
{

	motor[motorA]=k*(45-nMotorEncoder[motorA]);
wait1Msec(1);
}
}
