#pragma config(Sensor, S1,     T1,             sensorEV3_Touch)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void beat()
{
motor[mA]=-80;
while(nMotorEncoder[mA]>10) wait1Msec(1);
motor[mA]=20;
while(nMotorEncoder[mA]<30) wait1Msec(1);
motor[mA]=0;
}
task main()
{
motor[mA]=-10;
wait1Msec(500);
motor[mA]=0;
nMotorEncoder[mA]=0;
motor[mA]=20;
while(nMotorEncoder[mA]<30) wait1Msec(1);
motor[mA]=0;
while(true)
{
	beat();
	wait1Msec(1000);
		beat();
	wait1Msec(2000);
		beat();
	wait1Msec(3000);
}
}
