#pragma config(Sensor, S2,     Ls,             sensorEV3_Color)
#pragma config(Sensor, S3,     Gs,             sensorEV3_Gyro)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
float err, errold=0;
float kp=20, kd=0.003, ki=100, u, dt=0.001;
float up, ud, ui=0;
float scale=14;
  int L = SensorValue[Ls];
  playSound(soundBeepBeep);
     wait1Msec(2000);

while (true)
{
	err=L-SensorValue[Ls];
	up=kp*err;
	ui=ui+ki*err*dt;
	ud=kd*errold;
	errold=err;
	u=(up+ud+ui)/scale;
	motor[mB]=5+u;
	motor[mC]=5+u;
	wait1Msec(1);



}
}
