#pragma config(Sensor, S2,     Ls,             sensorEV3_Color)
#pragma config(Sensor, S3,     Gs,             sensorEV3_Gyro)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*void kalibrovka(){
	int Gyro=SensorValue[Gs];
	//wait1Msec(2000);
	playSound(soundBeepBeep);
		displayBigTextLine(2,"%d", SensorValue[Gs]);
wait1Msec(3000);
}*/

task main()
{
//kalibrovka();

float err, errold=0;
float kp=7, kd=70, ki=0.0005, u, dt=0;
float up, ud, ui=0;
float scale=1;
  int L = SensorValue[Ls];
  playSound(soundBeepBeep);
     wait1Msec(2000);

//	int Gyro=getGyroRate(Gs);
//	playSound(soundBeepBeep);
		//displayBigTextLine(2,"%d", getGyroRate(Gs));
//wait1Msec(3000);

while (true)
{

	err=L-SensorValue[Ls];
	up=kp*err;
	ui=ui+ki*err*dt;
	ud=kd*errold;
	errold=err;
	u=(up+ud+ui)/scale;
	motor[mB]=u;
	motor[mC]=u;
	wait1Msec(1);
			displayBigTextLine(2,"%d", getGyroRate(Gs));


}
}
