#pragma config(Sensor, S2,     Ls,             sensorEV3_Color)
#pragma config(Sensor, S3,     Gs,             sensorEV3_Gyro)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void kalibrovka(){
	int Gyro=SensorValue[Gs];
wait1Msec(2000);
playSound(soundBeepBeep);
}

task main(){
kalibrovka();
while (true){
displayBigTextLine(2,"%d", SensorValue[Gs]);
}
}
