#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int v1=100;
float v2=0;
float a=1.2;
while(v2<40)
{
	v2=v2+a;
	a=a-0.01;
	motor[mB]=v1;
	motor[mC]=v2;
	wait1Msec(100);
	}
	wait1Msec(8000);
		motor[mB]=0;
	motor[mC]=0;
}
