#pragma config(Sensor, S2,     Us,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task timer()
{
while(true)
{
clearTimer(T1);
while(time1(T1)<10000)wait1Msec(1);
motor[motorB]=-50;
motor[motorC]=-50;
wait1Msec(500);
motor[motorB]=50;
wait1Msec(500);
motor[motorB]=50;
}
}
task main()
{
startTask(timer);
while(true){
motor[motorB]=50;
motor[motorC]=50;
while(SensorValue[Us]>25) wait1Msec(1);
clearTimer(T1);
motor[motorB]=-50;
motor[motorC]=-50;
wait1Msec(500);
motor[motorB]=50;
wait1Msec(500);
}


}
