#pragma config(Sensor, S3,     Us,             sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     L,              sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task go()
{
int	C=SensorValue[L];
	while(true){
		while(SensorValue[L]>C){
motor[mB]=100;
motor[mC]=100;
}
while(SensorValue[Us]>35){
motor[mB]=50;
motor[mC]=-50;
}
}
}
task right()
{
int	C=SensorValue[L];
	while(true){
		while(SensorValue[Us]>35){
motor[mB]=50;
motor[mC]=-50;
}
while(SensorValue[L]>C){
	motor[mB]=100;
motor[mC]=100;
}
}
}
task left()
{
int	C=SensorValue[L];
	while(true){
		while(SensorValue[Us]>35){
motor[mB]=-50;
motor[mC]=50;
}
while(SensorValue[L]>C){
	motor[mB]=100;
motor[mC]=100;
}

}
}
task main()
{
	waitForButtonPress();
if (getButtonPress(buttonEnter)==1){
	startTask(go);
	}
if (getButtonPress(buttonRight)==1){
	startTask(right);
	}
	if (getButtonPress(buttonLeft)==1){
	startTask(left);
	}

}
