#pragma config(Sensor, S1,     Col,            sensorEV3_Color)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int v=100;
int gr=12;
int Sold;
float u, up, ud;
float kp=7;
float kd=17;

while(true){

	up=kp*(SensorValue[Col]-gr);
	ud=kd*(SensorValue[Col]-Sold);
	u=up+ud;
	motor[mB]=v+u;
	motor[mC]=v-u;
	Sold=SensorValue[Col];
	wait1Msec(1);
}

}
