
#pragma config(Sensor, S1,     Us,             sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     L2,             sensorEV3_Color)
#pragma config(Sensor, S3,     L1,             sensorEV3_Color)
#pragma config(Motor,  motorA,          mA,            tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (true){

	while (SensorValue[Us]>5)wait1Msec(1);
	nMotorEncoder[mB]=0;
	motor[mB]=10;
	motor[mC]=10;
	while(nMotorEncoder[mB]<-50)wait1Msec(1);

	motor[mB]=0;
	motor[mC]=0;
	wait1Msec(1000);

	nMotorEncoder[mA]=0;// manipulyator
motor[mA]=10;
while(nMotorEncoder[mA]<200)wait1Msec(1);

}

}
