#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <gyro.h>
#include <sumo.h>
#include <motors.h>

task main()
{
	wait1Msec(5000);
	search_l(55,100);
	turn_left(100,230);
	sumo_walking();
}
