#pragma config(Sensor, S1,     ,               sensorSONAR)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <display.h>
#include <functions.h>

task main()
{
	begin();
	while(true)
	{
		search();
		turn_to_skittle();
		check_skittle();
		if(color == 6) white_skittle();
		if(color == 1) black_skittle();
	}
	setLEDColor(ledRedPulse);
	end();
}
