#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <motors.h>
#include <sumo.h>
#include <display.h>

task main()
{
	wait1Msec(5000);
	search_l(100,40);
	//turn_left(55,100);
	sumo(25);
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;
}
