#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include <motors.h>
//#include <sumo.h>
//#include <display.h>

task main()
{
	int grey = 30;
	wait1Msec(5000);
	while(SensorValue[S1] >= grey)
	{
		motor[motorA] = -100;
		motor[motorB] = 100;
		motor[motorC] = 100;
		wait1Msec(1);
	}
}
