#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <motors.h>
#include <sumo.h>


task main()
{
	int grey = 45;

	wait1Msec(5000);
	search_r(100,40);
	turn_right(50,200);
	while(true)
	{
		motor[motorA] = -100;
		motor[motorB] = 100;
		motor[motorC] = 100;
		if(SensorValue[S1] <= grey) break;
		wait1Msec(1);
	}
	turn_back(100,100);

}
