#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <gyro.h>
#include <sumo.h>
#include <motors.h>

task main()
{
	int grey = 45;
	wait1Msec(5000);
	while(true)
	{
		motor[motorA] = -100;
		motor[motorB] = 100;
		motor[motorC] = 100;
		if(SensorValue[S1] <= grey) break;
		wait1Msec(1);
	}

	turn_back(100,100);
}
