#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include<line.h>
#include<labirint.h>

task main()
{
	turn_forward(100,300);
	go_line(
	/* k1 */2.85,
	/* k2 */20,
	/* kv */2.85,
	/* vm */100
	);
	turn_forward(100,200); // forward
	turn_right(100,400); //right
	go_line(
	/* k1 */2.85,
	/* k2 */20,
	/* kv */2.85,
	/* vm */100
	);
	labirint_1(6);
	turn_right(100,400);
	labirint_1(6);
	turn_left(100,400);
	turn_forward(100,400);
	go_line(
	/* k1 */2.85,
	/* k2 */20,
	/* kv */2.85,
	/* vm */100
	);
	turn_left(100,150);
	turn_forward(100,100);
	go_line(
	/* k1 */2.85,
	/* k2 */20,
	/* kv */2.85,
	/* vm */100
	);
	labirint_1(6);
	turn_left(100,400);
	labirint_1(6);
	turn_right(100,400);
	labirint_1(6);
	turn_right(100,400);
	labirint_1(6);
	turn_left(100,400);
	labirint_1(6);
	turn_left(100,400);
	turn_forward(100,600);
	go_line(
	/* k1 */2.85,
	/* k2 */20,
	/* kv */2.85,
	/* vm */100
	);
	turn_forward(100,800);
}
